"""empty message

Revision ID: 2566a1fa8aaf
Revises: db1a455f6c84
Create Date: 2020-11-17 20:54:42.432904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2566a1fa8aaf'
down_revision = 'db1a455f6c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artists', ['name'])
    op.create_unique_constraint(None, 'venues', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    # ### end Alembic commands ###
